#!/usr/bin/python
import random
import objects
all_the_things = {
"zombie1": objects.Monster(key="zombie1",name="Zombie",symbol="Z",description="Your basic shambling zombie. \"Brains!\"",longdesc="This decaying corpse shuffles along slowly. Despite its constant hunger for brains, it shows a distinct lack of enthusiasm.",defense={'melee':30},attacks={'unarmed':objects.roll(1,4)},speed=80,inventory=[],scared_at=0,brave_at=90),
"snake1": objects.Monster(key="snake1",name="Snake",symbol="s",description="A snake. Not poisonous, yet.",longdesc="Why did it have to be snakes? Luckily, this one is a little green one that looks pretty harmless.",defense={'melee':30},attacks={'unarmed':objects.roll(1,4)},speed=60,accuracy=80,inventory=[],scared_at=50,brave_at=90,sleepy=50),
"syrup1": objects.Monster(key="syrup1",name="breakfast syrup monster",symbol="o",description="A slimy mass of sugary protoplasm.",longdesc="A creature spawned of hunger, mad science, and low-budget ingredients. It takes the shape of a giant amoeba, with a vague maple-ish color and an even more vague maple-ish scent. Its strange aftertaste and too-thick viscoscity betray its cheapness. It creeps slowly along with a quiet malevolence, sticking to everything it touches.",level=1,attacks={'unarmed':objects.roll(1,4)},speed=120,proc="sticky"),
"syrup2": objects.Monster(key="syrup2",name="agave ooze monster",symbol="o",description="A sweet, sticky ooze, somewhat runny.",longdesc="One of two products harvested from the Dire Agave plant. Possibly escaped from a planar rift near a health food store. This ooze has a low glycemic index, and may prove a durable opponent.",level=8,attacks={'unarmed':objects.roll(1,6)},speed=60),
"syrup3": objects.Monster(key="syrup3",name="honey ooze monster",symbol="o",description="A very viscous golden ooze that smells of flowers.",longdesc="A very thick, very sweet ooze monster that spawns in Dire Bee hives. Though it is mostly a golden color, specks of pollen are visible in it, and along the edges it has taken a slightly crystalline texture.",level=15,attacks={'unarmed':objects.roll(1,10)},speed=70),
"syrup4": objects.Monster(key="syrup4",name="maple syrup monster",symbol="o",description="An aromatic brown ooze.",longdesc="The Maple Syrup Monster is a tragic creature. It is somewhat rare, as it originates only in the extracted sap of a Maple Treant. Though the tree-people are peaceful, their stolen sap often becomes vengeful and violent. The resulting monster can fill an entire dungeon floor with a delicious sweet scent.",level=22,attacks={'unarmed':objects.roll(2,6)},speed=50),
"syrup5": objects.Monster(key="syrup5",name="Boston Molasses Monster",symbol="O",description="The ur-ooze of sugar oozes!",longdesc="A massive, lake-sized blob of molasses, first sighted in Boston in 1919. The 2.3 million gallon wave of molasses escaped from its tank, crushed buildings, bent girders, and killed 22 people. Now it's living in your data center's dungeon as the king of the sugar oozes.",indef_article="the ",level=33,attacks={'unarmed':objects.roll(3,6)},speed=50)
}
